apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-config
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
data:
  PAPERLESS_TIME_ZONE: {{ .Values.paperless.config.timezone | quote }}
  PAPERLESS_ALLOWED_HOSTS: {{ .Values.paperless.config.allowedHosts | quote }}
  PAPERLESS_CORS_ALLOWED_HOSTS: {{ .Values.paperless.config.corsAllowedHosts | quote }}
  PAPERLESS_STATIC_URL: {{ .Values.paperless.config.staticUrl | quote }}
  PAPERLESS_OCR_LANGUAGES: {{ .Values.paperless.config.ocrLanguages | quote }}
  PAPERLESS_TASK_WORKERS: {{ .Values.paperless.config.taskWorkers | quote }}
  PAPERLESS_THREADS_PER_WORKER: {{ .Values.paperless.config.threadsPerWorker | quote }}
  {{- if .Values.paperless.config.forceScriptName }}
  PAPERLESS_FORCE_SCRIPT_NAME: {{ .Values.paperless.config.forceScriptName | quote }}
  {{- end }}
  
  # Admin user configuration
  PAPERLESS_ADMIN_USER: {{ .Values.paperless.admin.username | quote }}
  PAPERLESS_ADMIN_MAIL: {{ .Values.paperless.admin.email | quote }}
  
  # Database configuration
  PAPERLESS_DBENGINE: {{ .Values.externalDatabase.type | default "postgresql" | quote }}
  PAPERLESS_DBHOST: {{ include "paperless-ngx.databaseHost" . | quote }}
  PAPERLESS_DBPORT: {{ include "paperless-ngx.databasePort" . | quote }}
  PAPERLESS_DBNAME: {{ include "paperless-ngx.databaseName" . | quote }}
  PAPERLESS_DBUSER: {{ include "paperless-ngx.databaseUsername" . | quote }}
  
  # Redis configuration (password will be injected via environment variable)
  PAPERLESS_REDIS: redis://{{ include "paperless-ngx.redisHost" . }}:{{ include "paperless-ngx.redisPort" . }}/{{ .Values.externalRedis.database | default 0 }}
  
  # Email configuration
  {{- if .Values.paperless.config.email.enabled }}
  PAPERLESS_EMAIL_HOST: {{ .Values.paperless.config.email.host | quote }}
  PAPERLESS_EMAIL_PORT: {{ .Values.paperless.config.email.port | quote }}
  PAPERLESS_EMAIL_HOST_USER: {{ .Values.paperless.config.email.hostUser | quote }}
  PAPERLESS_EMAIL_USE_TLS: {{ .Values.paperless.config.email.useTls | quote }}
  PAPERLESS_EMAIL_USE_SSL: {{ .Values.paperless.config.email.useSSL | quote }}
  PAPERLESS_DEFAULT_FROM_EMAIL: {{ .Values.paperless.config.email.from | quote }}
  {{- end }}